-- CreateEnum
CREATE TYPE "PAYMENT_FREQUENCY" AS ENUM ('ONE_TIME_PAYMENT', 'WEAKLY_PAYMENT', 'MONTHLY_PAYMENT', 'YEARLY_PAYMENT');

-- AlterTable
ALTER TABLE "Class" ADD COLUMN     "paymentFrequency" "PAYMENT_FREQUENCY" NOT NULL DEFAULT 'ONE_TIME_PAYMENT',
ADD COLUMN     "price" INTEGER;

-- AlterTable
ALTER TABLE "ClassMessage" ADD COLUMN     "replyToMessageId" INTEGER;

-- AddForeignKey
ALTER TABLE "ClassMessage" ADD CONSTRAINT "ClassMessage_replyToMessageId_fkey" FOREIGN KEY ("replyToMessageId") REFERENCES "ClassMessage"("id") ON DELETE SET NULL ON UPDATE CASCADE;
