-- CreateEnum
CREATE TYPE "VERIFICATION_CODE_SOURCE" AS ENUM ('WHATSAPP', 'SMS', 'EMAIL');

-- CreateEnum
CREATE TYPE "VERIFICATION_CODE_TYPE" AS ENUM ('REGISTER', 'LOGIN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "emailVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "phoneVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "verificationCode" INTEGER,
ADD COLUMN     "verificationCodeSource" "VERIFICATION_CODE_SOURCE",
ADD COLUMN     "verificationCodeType" "VERIFICATION_CODE_TYPE";
