-- CreateEnum
CREATE TYPE "MESSAGE_TYPE" AS ENUM ('TEXT', 'IMAGE');

-- CreateEnum
CREATE TYPE "CHAT_TYPE" AS ENUM ('ONE_TO_ONE');

-- AlterTable
ALTER TABLE "Chat" ADD COLUMN     "type" "CHAT_TYPE" NOT NULL DEFAULT 'ONE_TO_ONE',
ADD COLUMN     "unreadCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Message" ADD COLUMN     "contentType" "MESSAGE_TYPE" NOT NULL DEFAULT 'TEXT';
