export const errorMessage = {
  USER_EXISTS: "USER_EXISTS",
  MISSING_PARAMS: "MISSING_PARAMS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER: "INTERNAL_SERVER",
  INCORRECT_DATA: "INCORRECT_DATA",
  WRONG_AUTH_METHOD: "WRONG_AUTH_METHOD",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  FLOW_ERROR: "FLOW_ERROR",
  EXISTING_DATA: "EXISTING_DATA",
  UNAUTHORISED: "UNAUTHORISED",
  NOT_ALLOWED: "NOT_ALLOWED",
  REDUNDANT_REQUEST: "REDUNDANT_REQUEST",
  TOKEN_MISSING: "TOKEN_MISSING",
  DB_ISSUE: "DB_ISSUE",
  USER_BLOCKED: "USER_BLOCKED",
  DUPLICATE_USERNAME: "DUPLICATE_USERNAME",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  LIMIT_EXHAUSTED: "LIMIT_EXHAUSTED",
  NO_PAYMENT: "NO_PAYMENT",
  DATA_MISMATCH: "DATA_MISMATCH",
  SMS_ISSUE: "SMS_ISSUE",
  CLASS_NOT_PAID: "CLASS_NOT_PAID",
  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
};

export const errorCode = {
  GENERIC: 400,
  UNAUTHORISED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER: 500,
};

export const successMessages = {
  CREATED: "CREATED",
  SUCCESS: "SUCCESS",
  FETCHED: "FETCHED",
  UPDATED: "UPDATED",
  JOINED_CLASS: "JOINED_CLASS",
};
