export const errorMessage = {
  USER_EXISTS: "USER_EXISTS",
  MISSING_PARAMS: "MISSING_PARAMS",
  USER_NOT_ROUND: "USER_NOT_ROUND",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER: "INTERNAL_SERVER",
  INCORRECT_DATA: "INCORRECT_DATA",
};

export const errorCode = {
  GENERIC: 400,
  UNAUTHORISED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER: 500,
};
