-- CreateEnum
CREATE TYPE "PATRON_CREATOR_STATUS" AS ENUM ('ACTIVE', 'EXPIRED', 'PENDING');

-- AlterTable
ALTER TABLE "PatronCreator" ADD COLUMN     "status" "PATRON_CREATOR_STATUS" NOT NULL DEFAULT 'PENDING';
