import * as Joi from "joi";

export const userPostSchema = Joi.object({
  authorId: Joi.string().required(),
  type: Joi.string().valid("TEXT", "FREE").required(),
  visibility: Joi.string().valid("EVERYONE").required(),
  allowComments: Joi.boolean().required(),
  createdAt: Joi.date().iso(),
  updatedAt: Joi.date().iso(),
  pollId: Joi.string(),
  email: Joi.string().email().lowercase(),
  firstName: Joi.string().min(1),
  lastName: Joi.string().min(1),
  username: Joi.string(),
  phoneNumber: Joi.string(),
  countryCode: Joi.string(),
  profileImage: Joi.string().uri(),
  coverImage: Joi.string().uri(),
  isCreator: Joi.boolean(),
  gender: Joi.string().valid("MALE", "FEMALE", "OTHER"),
  role: Joi.array().items(Joi.string().valid("PATRON", "CREATOR", "ADMIN")),
  description: Joi.string(),
  options: Joi.string(),
  selectedOptions: Joi.string(),
  title: Joi.string().required(),
  videoUrl: Joi.string(),
  packages: Joi.array().items(Joi.string()).required(),
  userPostId: Joi.string(),
});
