import * as Joi from "joi";

export const userPostSchema = Joi.object({
  pollId: Joi.number(),
  postId: Joi.number(),
  selectedId: Joi.number(),
  authorId: Joi.number(),
  type: Joi.string().valid("TEXT", "FREE"),
  visibility: Joi.string().valid("EVERYONE"),
  allowComments: Joi.boolean(),
  email: Joi.string().email().lowercase(),
  firstName: Joi.string().min(1),
  lastName: Joi.string().min(1),
  username: Joi.string(),
  phoneNumber: Joi.string(),
  countryCode: Joi.string(),
  profileImage: Joi.string().uri(),
  coverImage: Joi.string().uri(),
  isCreator: Joi.boolean(),
  gender: Joi.string().valid("MALE", "FEMALE", "OTHER"),
  role: Joi.array().items(Joi.string().valid("PATRON", "CREATOR", "ADMIN")),
  description: Joi.string(),
  options: Joi.string(),
  selectedOptions: Joi.string(),
  title: Joi.string(),
  videoUrl: Joi.string(),
  packages: Joi.array().items(Joi.string()),
  userPostId: Joi.number(),
});
